//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace mess.EntFrame
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MyDataEntities4 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MyDataEntities4 object using the connection string found in the 'MyDataEntities4' section of the application configuration file.
        /// </summary>
        public MyDataEntities4() : base("name=MyDataEntities4", "MyDataEntities4")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyDataEntities4 object.
        /// </summary>
        public MyDataEntities4(string connectionString) : base(connectionString, "MyDataEntities4")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyDataEntities4 object.
        /// </summary>
        public MyDataEntities4(EntityConnection connection) : base(connection, "MyDataEntities4")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Admin_Data> Admin_Data
        {
            get
            {
                if ((_Admin_Data == null))
                {
                    _Admin_Data = base.CreateObjectSet<Admin_Data>("Admin_Data");
                }
                return _Admin_Data;
            }
        }
        private ObjectSet<Admin_Data> _Admin_Data;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Admin_Data EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdmin_Data(Admin_Data admin_Data)
        {
            base.AddObject("Admin_Data", admin_Data);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyDataModel1", Name="Admin_Data")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Admin_Data : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Admin_Data object.
        /// </summary>
        /// <param name="iDad">Initial value of the IDad property.</param>
        /// <param name="fname">Initial value of the Fname property.</param>
        /// <param name="lname">Initial value of the Lname property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="uname">Initial value of the Uname property.</param>
        /// <param name="pword">Initial value of the Pword property.</param>
        public static Admin_Data CreateAdmin_Data(global::System.Int32 iDad, global::System.String fname, global::System.String lname, global::System.String email, global::System.String uname, global::System.String pword)
        {
            Admin_Data admin_Data = new Admin_Data();
            admin_Data.IDad = iDad;
            admin_Data.Fname = fname;
            admin_Data.Lname = lname;
            admin_Data.Email = email;
            admin_Data.Uname = uname;
            admin_Data.Pword = pword;
            return admin_Data;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDad
        {
            get
            {
                return _IDad;
            }
            set
            {
                if (_IDad != value)
                {
                    OnIDadChanging(value);
                    ReportPropertyChanging("IDad");
                    _IDad = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDad");
                    OnIDadChanged();
                }
            }
        }
        private global::System.Int32 _IDad;
        partial void OnIDadChanging(global::System.Int32 value);
        partial void OnIDadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Fname
        {
            get
            {
                return _Fname;
            }
            set
            {
                OnFnameChanging(value);
                ReportPropertyChanging("Fname");
                _Fname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Fname");
                OnFnameChanged();
            }
        }
        private global::System.String _Fname;
        partial void OnFnameChanging(global::System.String value);
        partial void OnFnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lname
        {
            get
            {
                return _Lname;
            }
            set
            {
                OnLnameChanging(value);
                ReportPropertyChanging("Lname");
                _Lname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lname");
                OnLnameChanged();
            }
        }
        private global::System.String _Lname;
        partial void OnLnameChanging(global::System.String value);
        partial void OnLnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Uname
        {
            get
            {
                return _Uname;
            }
            set
            {
                OnUnameChanging(value);
                ReportPropertyChanging("Uname");
                _Uname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Uname");
                OnUnameChanged();
            }
        }
        private global::System.String _Uname;
        partial void OnUnameChanging(global::System.String value);
        partial void OnUnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pword
        {
            get
            {
                return _Pword;
            }
            set
            {
                OnPwordChanging(value);
                ReportPropertyChanging("Pword");
                _Pword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pword");
                OnPwordChanged();
            }
        }
        private global::System.String _Pword;
        partial void OnPwordChanging(global::System.String value);
        partial void OnPwordChanged();

        #endregion

    
    }

    #endregion

    
}
